let strings = {};

strings.E1 = {
  notes: {
     0: { pos:  0, note: 'E',  noteAlt: '',   octave: '2'},
     1: { pos:  1, note: 'F',  noteAlt: '',   octave: '2'},
     2: { pos:  2, note: 'F#', noteAlt: 'Gb', octave: '2'},
     3: { pos:  3, note: 'G',  noteAlt: '',   octave: '2'},
     4: { pos:  4, note: 'G#', noteAlt: 'Ab', octave: '2'},
     5: { pos:  5, note: 'A',  noteAlt: '',   octave: '2'},
     6: { pos:  6, note: 'A#', noteAlt: 'Bb', octave: '2'},
     7: { pos:  7, note: 'B',  noteAlt: '',   octave: '2'},
     8: { pos:  8, note: 'C',  noteAlt: '',   octave: '3'},
     9: { pos:  9, note: 'C#', noteAlt: 'Db', octave: '3'},
    10: { pos: 10, note: 'D',  noteAlt: '',   octave: '3'},
    11: { pos: 11, note: 'D#', noteAlt: 'Eb', octave: '3'},
    12: { pos: 12, note: 'E',  noteAlt: '',   octave: '3'},
    13: { pos: 13, note: 'F',  noteAlt: '',   octave: '3'},
    14: { pos: 14, note: 'F#', noteAlt: 'Gb', octave: '3'},
    15: { pos: 15, note: 'G',  noteAlt: '',   octave: '3'},
    16: { pos: 16, note: 'G#', noteAlt: 'Ab', octave: '3'},
    17: { pos: 17, note: 'A',  noteAlt: '',   octave: '3'},
    18: { pos: 18, note: 'A#', noteAlt: 'Bb', octave: '3'},
    19: { pos: 19, note: 'B',  noteAlt: '',   octave: '3'},
    20: { pos: 20, note: 'C',  noteAlt: '',   octave: '4'},
    21: { pos: 21, note: 'C#', noteAlt: 'Db', octave: '4'},
    22: { pos: 22, note: 'D',  noteAlt: '',   octave: '4'},
    23: { pos: 23, note: 'D#', noteAlt: 'Eb', octave: '4'},
    24: { pos: 24, note: 'E',  noteAlt: '',   octave: '4'}
  }
};

strings.A1 = {
  notes: {
     0: { pos:  0, note: 'A',  noteAlt: '',   octave: '2'},
     1: { pos:  1, note: 'A#', noteAlt: 'Bb', octave: '2'},
     2: { pos:  2, note: 'B',  noteAlt: '',   octave: '2'},
     3: { pos:  3, note: 'C',  noteAlt: '',   octave: '3'},
     4: { pos:  4, note: 'C#', noteAlt: 'Db', octave: '3'},
     5: { pos:  5, note: 'D',  noteAlt: '',   octave: '3'},
     6: { pos:  6, note: 'D#', noteAlt: 'Eb', octave: '3'},
     7: { pos:  7, note: 'E',  noteAlt: '',   octave: '3'},
     8: { pos:  8, note: 'F',  noteAlt: '',   octave: '3'},
     9: { pos:  9, note: 'F#', noteAlt: 'Gb', octave: '3'},
    10: { pos: 10, note: 'G',  noteAlt: '',   octave: '3'},
    11: { pos: 11, note: 'G#', noteAlt: 'Ab', octave: '3'},
    12: { pos: 12, note: 'A',  noteAlt: '',   octave: '3'},
    13: { pos: 13, note: 'A#', noteAlt: 'Bb', octave: '3'},
    14: { pos: 14, note: 'B',  noteAlt: '',   octave: '3'},
    15: { pos: 15, note: 'C',  noteAlt: '',   octave: '4'},
    16: { pos: 16, note: 'C#', noteAlt: 'Db', octave: '4'},
    17: { pos: 17, note: 'D',  noteAlt: '',   octave: '4'},
    18: { pos: 18, note: 'D#', noteAlt: 'Eb', octave: '4'},
    19: { pos: 19, note: 'E',  noteAlt: '',   octave: '4'},
    20: { pos: 20, note: 'F',  noteAlt: '',   octave: '4'},
    21: { pos: 21, note: 'F#', noteAlt: 'Gb', octave: '4'},
    22: { pos: 22, note: 'G',  noteAlt: '',   octave: '4'},
    23: { pos: 23, note: 'G#', noteAlt: 'Ab', octave: '4'},
    24: { pos: 24, note: 'A',  noteAlt: '',   octave: '4'},
  }
};

strings.D1 = {
  notes: {
     0: { pos:  0, note: 'D',  noteAlt: '',   octave: '3'},
     1: { pos:  1, note: 'D#', noteAlt: 'Eb', octave: '3'},
     2: { pos:  2, note: 'E',  noteAlt: '',   octave: '3'},
     3: { pos:  3, note: 'F',  noteAlt: '',   octave: '3'},
     4: { pos:  4, note: 'F#', noteAlt: 'Gb', octave: '3'},
     5: { pos:  5, note: 'G',  noteAlt: '',   octave: '3'},
     6: { pos:  6, note: 'G#', noteAlt: 'Ab', octave: '3'},
     7: { pos:  7, note: 'A',  noteAlt: '',   octave: '3'},
     8: { pos:  8, note: 'A#', noteAlt: 'Bb', octave: '3'},
     9: { pos:  9, note: 'B',  noteAlt: '',   octave: '3'},
    10: { pos: 10, note: 'C',  noteAlt: '',   octave: '4'},
    11: { pos: 11, note: 'C#', noteAlt: 'Db', octave: '4'},
    12: { pos: 12, note: 'D',  noteAlt: '',   octave: '4'},
    13: { pos: 13, note: 'D#', noteAlt: 'Eb', octave: '4'},
    14: { pos: 14, note: 'E',  noteAlt: '',   octave: '4'},
    15: { pos: 15, note: 'F',  noteAlt: '',   octave: '4'},
    16: { pos: 16, note: 'F#', noteAlt: 'Gb', octave: '4'},
    17: { pos: 17, note: 'G',  noteAlt: '',   octave: '4'},
    18: { pos: 18, note: 'G#', noteAlt: 'Ab', octave: '4'},
    19: { pos: 19, note: 'A',  noteAlt: '',   octave: '4'},
    20: { pos: 20, note: 'A#', noteAlt: 'Bb', octave: '4'},
    21: { pos: 21, note: 'B',  noteAlt: '',   octave: '4'},
    22: { pos: 22, note: 'C',  noteAlt: '',   octave: '5'},
    23: { pos: 23, note: 'C#', noteAlt: 'Db', octave: '5'},
    24: { pos: 24, note: 'D',  noteAlt: '',   octave: '5'},
  }
};

strings.G1 = {
  notes: {
     0: { pos:  0, note: 'G',  noteAlt: '',   octave: '3'},
     1: { pos:  1, note: 'G#', noteAlt: 'Ab', octave: '3'},
     2: { pos:  2, note: 'A',  noteAlt: '',   octave: '3'},
     3: { pos:  3, note: 'A#', noteAlt: 'Bb', octave: '3'},
     4: { pos:  4, note: 'B',  noteAlt: '',   octave: '3'},
     5: { pos:  5, note: 'C',  noteAlt: '',   octave: '4'},
     6: { pos:  6, note: 'C#', noteAlt: 'Db', octave: '4'},
     7: { pos:  7, note: 'D',  noteAlt: '',   octave: '4'},
     8: { pos:  8, note: 'D#', noteAlt: 'Eb', octave: '4'},
     9: { pos:  9, note: 'E',  noteAlt: '',   octave: '4'},
    10: { pos: 10, note: 'F',  noteAlt: '',   octave: '4'},
    11: { pos: 11, note: 'F#', noteAlt: 'Gb', octave: '4'},
    12: { pos: 12, note: 'G',  noteAlt: '',   octave: '4'},
    13: { pos: 13, note: 'G#', noteAlt: 'Ab', octave: '4'},
    14: { pos: 14, note: 'A',  noteAlt: '',   octave: '4'},
    15: { pos: 15, note: 'A#', noteAlt: 'Bb', octave: '4'},
    16: { pos: 16, note: 'B',  noteAlt: '',   octave: '4'},
    17: { pos: 17, note: 'C',  noteAlt: '',   octave: '5'},
    18: { pos: 18, note: 'C#', noteAlt: 'Db', octave: '5'},
    19: { pos: 19, note: 'D',  noteAlt: '',   octave: '5'},
    20: { pos: 20, note: 'D#', noteAlt: 'Eb', octave: '5'},
    21: { pos: 21, note: 'E',  noteAlt: '',   octave: '5'},
    22: { pos: 22, note: 'F',  noteAlt: '',   octave: '5'},
    23: { pos: 23, note: 'F#', noteAlt: 'Gb', octave: '5'},
    24: { pos: 24, note: 'G',  noteAlt: '',   octave: '5'},
  }
};

strings.B1 = {
  notes: {
     0: { pos:  0, note: 'B',  noteAlt: '',   octave: '3'},
     1: { pos:  1, note: 'C',  noteAlt: '',   octave: '4'},
     2: { pos:  2, note: 'C#', noteAlt: 'Db', octave: '4'},
     3: { pos:  3, note: 'D',  noteAlt: '',   octave: '4'},
     4: { pos:  4, note: 'D#', noteAlt: 'Eb', octave: '4'},
     5: { pos:  5, note: 'E',  noteAlt: '',   octave: '4'},
     6: { pos:  6, note: 'F',  noteAlt: '',   octave: '4'},
     7: { pos:  7, note: 'F#', noteAlt: 'Gb', octave: '4'},
     8: { pos:  8, note: 'G',  noteAlt: '',   octave: '4'},
     9: { pos:  9, note: 'G#', noteAlt: 'Ab', octave: '4'},
    10: { pos: 10, note: 'A',  noteAlt: '',   octave: '4'},
    11: { pos: 11, note: 'A#', noteAlt: 'Bb', octave: '4'},
    12: { pos: 12, note: 'B',  noteAlt: '',   octave: '4'},
    13: { pos: 13, note: 'C',  noteAlt: '',   octave: '5'},
    14: { pos: 14, note: 'C#', noteAlt: 'Db', octave: '5'},
    15: { pos: 15, note: 'D',  noteAlt: '',   octave: '5'},
    16: { pos: 16, note: 'D#', noteAlt: 'Eb', octave: '5'},
    17: { pos: 17, note: 'E',  noteAlt: '',   octave: '5'},
    18: { pos: 18, note: 'F',  noteAlt: '',   octave: '5'},
    19: { pos: 19, note: 'F#', noteAlt: 'Gb', octave: '5'},
    20: { pos: 20, note: 'G',  noteAlt: '',   octave: '5'},
    21: { pos: 21, note: 'G#', noteAlt: 'Ab', octave: '5'},
    22: { pos: 22, note: 'A',  noteAlt: '',   octave: '5'},
    23: { pos: 23, note: 'A#', noteAlt: 'Bb', octave: '5'},
    24: { pos: 24, note: 'B',  noteAlt: '',   octave: '5'},
  }
};

strings.E2 = {
  notes: {
     0: { pos:  0, note: 'E',  noteAlt: '',   octave: '4'},
     1: { pos:  1, note: 'F',  noteAlt: '',   octave: '4'},
     2: { pos:  2, note: 'F#', noteAlt: 'Gb', octave: '4'},
     3: { pos:  3, note: 'G',  noteAlt: '',   octave: '4'},
     4: { pos:  4, note: 'G#', noteAlt: 'Ab', octave: '4'},
     5: { pos:  5, note: 'A',  noteAlt: '',   octave: '4'},
     6: { pos:  6, note: 'A#', noteAlt: 'Bb', octave: '4'},
     7: { pos:  7, note: 'B',  noteAlt: '',   octave: '4'},
     8: { pos:  8, note: 'C',  noteAlt: '',   octave: '5'},
     9: { pos:  9, note: 'C#', noteAlt: 'Db', octave: '5'},
    10: { pos: 10, note: 'D',  noteAlt: '',   octave: '5'},
    11: { pos: 11, note: 'D#', noteAlt: 'Eb', octave: '5'},
    12: { pos: 12, note: 'E',  noteAlt: '',   octave: '5'},
    13: { pos: 13, note: 'F',  noteAlt: '',   octave: '5'},
    14: { pos: 14, note: 'F#', noteAlt: 'Gb', octave: '5'},
    15: { pos: 15, note: 'G',  noteAlt: '',   octave: '5'},
    16: { pos: 16, note: 'G#', noteAlt: 'Ab', octave: '5'},
    17: { pos: 17, note: 'A',  noteAlt: '',   octave: '5'},
    18: { pos: 18, note: 'A#', noteAlt: 'Bb', octave: '5'},
    19: { pos: 19, note: 'B',  noteAlt: '',   octave: '5'},
    20: { pos: 20, note: 'C',  noteAlt: '',   octave: '6'},
    21: { pos: 21, note: 'C#', noteAlt: 'Db', octave: '6'},
    22: { pos: 22, note: 'D',  noteAlt: '',   octave: '6'},
    23: { pos: 23, note: 'D#', noteAlt: 'Eb', octave: '6'},
    24: { pos: 24, note: 'E',  noteAlt: '',   octave: '6'},
  }
};

export notes;
